config/routes.rb
Marsrover::Application.routes.draw do
  get "version/index"

  devise_for :users

  resources :rovers

  resources :grids

  get "home/index"
  root :to => 'home#index'

end

app/models/grid.rb
class Grid < ActiveRecord::Base
  attr_accessible :breadth, :length

  validates_presence_of :length, :breadth, :on => :create

  validates :length, :breadth, :numericality => { :only_integer => true, :greater_than => 2, :less_than => 100}
  validate :is_it_square

  def is_it_square
    if (length == breadth)
       errors.add(:length, "Latest research and our experience shows that a rectangular region is more effective for this kind of mission.")
    end  
  end

end

app/models/rover.rb
class Rover < ActiveRecord::Base
  attr_accessible :landing_x_axis, :landing_y_axis, :target_x_axis, :target_y_axis

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable, :recoverable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  before_filter :authenticate_user!
  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grids }
    end
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
    @grid = Grid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/new
  # GET /grids/new.json
  def new
    @grid = Grid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/1/edit
  def edit
    @grid = Grid.find(params[:id])
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(params[:grid])

    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render json: @grid, status: :created, location: @grid }
      else
        format.html { render action: "new" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grids/1
  # PUT /grids/1.json
  def update
    @grid = Grid.find(params[:id])

    respond_to do |format|
      if @grid.update_attributes(params[:grid])
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid = Grid.find(params[:id])
    @grid.destroy

    respond_to do |format|
      format.html { redirect_to grids_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rovers_controller.rb
class RoversController < ApplicationController
  before_filter :authenticate_user!
  # GET /rovers
  # GET /rovers.json
  def index
    @rovers = Rover.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rovers }
    end
  end

  # GET /rovers/1
  # GET /rovers/1.json
  def show
    @rover = Rover.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rover }
    end
  end

  # GET /rovers/new
  # GET /rovers/new.json
  def new
    @rover = Rover.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rover }
    end
  end

  # GET /rovers/1/edit
  def edit
    @rover = Rover.find(params[:id])
  end

  # POST /rovers
  # POST /rovers.json
  def create
    @rover = Rover.new(params[:rover])

    respond_to do |format|
      if @rover.save
        format.html { redirect_to @rover, notice: 'Rover was successfully created.' }
        format.json { render json: @rover, status: :created, location: @rover }
      else
        format.html { render action: "new" }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rovers/1
  # PUT /rovers/1.json
  def update
    @rover = Rover.find(params[:id])

    respond_to do |format|
      if @rover.update_attributes(params[:rover])
        format.html { redirect_to @rover, notice: 'Rover was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rovers/1
  # DELETE /rovers/1.json
  def destroy
    @rover = Rover.find(params[:id])
    @rover.destroy

    respond_to do |format|
      format.html { redirect_to rovers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/version_controller.rb
class VersionController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rovers_helper.rb
module RoversHelper
end

app/helpers/version_helper.rb
module VersionHelper
end

app/views/grids/_form.html.erb
<%= form_for @grid, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :length, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :length, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :breadth, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :breadth, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                grids_path, :class => 'btn' %>
  </div>
<% end %>

app/views/grids/edit.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grids/index.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:length) %></th>
      <th><%= model_class.human_attribute_name(:breadth) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @grids.each do |grid| %>
      <tr>
        <td><%= link_to grid.created_at, grid_path(grid) %></td>
        <td><%= grid.length %></td>
        <td><%= grid.breadth %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_grid_path(grid), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      grid_path(grid),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_grid_path,
            :class => 'btn btn-primary' %>

app/views/grids/new.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/grids/show.html.erb
<%- model_class = Grid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<% @a = Array.new(@grid.length) {Array.new(@grid.breadth) {0}} %>
<p>The following coordinates are yet to be seen...</p>
<% for x in 0..@grid.length-1 %>
  <br>
  <% for y in 0..@grid.breadth-1 %>
    <% next if @a[x][y]==1 %>
    ( <%= x %>  , <%= y %>  )
  <% end %>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:length) %>:</strong></dt>
  <dd><%= @grid.length %></dd>
  <dt><strong><%= model_class.human_attribute_name(:breadth) %>:</strong></dt>
  <dd><%= @grid.breadth %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              grids_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_grid_path(@grid), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              grid_path(@grid),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NASA - Mars Mission 2012</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="background-image:url('/images/sky.jpg');">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/home/index">NASA - Mars Mission 2012</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", "/home/index" %></li>
            <li><%= link_to "Report a bug" %></li>
            <li><%= link_to "Launch a new rover", "/rovers/new" %></li>
            <li><%= link_to "Get Help", "/grids/(self.id)" %></li>
            <li><%= link_to "Version Information", "/version/index" %></li>
	    <% if user_signed_in? %>
	    Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path %> |
            <%= link_to "Login", new_user_session_path %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

  <div class="container">
    <div class="row">
      <div class="span7"><%= yield %></div>
      <div class="span5">
        <h2>Statement by the President on Curiosity Landing on Mars</h2>
        <h5>THE WHITE HOUSE</h5>
	<h5>Office of the Press Secretary</h5>
        <p>August 6, 2012</p>
	<p>Tonight, on the planet Mars, the United States of America made history.</p>
	<p>The successful landing of Curiosity – the most sophisticated roving laboratory ever to land on another planet – marks an unprecedented feat of technology that will stand as a point of national pride far into the future. It proves that even the longest of odds are no match for our unique blend of ingenuity and determination.</p>
	<p>Tonight’s success, delivered by NASA, parallels our major steps forward towards a vision for a new partnership with American companies to send American astronauts into space on American spacecraft. That partnership will save taxpayer dollars while allowing NASA to do what it has always done best – push the very boundaries of human knowledge. And tonight’s success reminds us that our preeminence – not just in space, but here on Earth – depends on continuing to invest wisely in the innovation, technology, and basic research that has always made our economy the envy of the world.</p>
	<p>I congratulate and thank all the men and women of NASA who made this remarkable accomplishment a reality – and I eagerly await what Curiosity has yet to discover.</p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/rovers/_form.html.erb
<%= form_for @rover, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :landing_x_axis, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :landing_x_axis, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :landing_y_axis, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :landing_y_axis, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :target_x_axis, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :target_x_axis, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :target_y_axis, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :target_y_axis, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rovers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rovers/edit.html.erb
<%- model_class = Rover -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rovers/index.html.erb
<%- model_class = Rover -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:landing_x_axis) %></th>
      <th><%= model_class.human_attribute_name(:landing_y_axis) %></th>
      <th><%= model_class.human_attribute_name(:target_x_axis) %></th>
      <th><%= model_class.human_attribute_name(:target_y_axis) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rovers.each do |rover| %>
      <tr>
        <td><%= link_to rover.created_at, rover_path(rover) %></td>
        <td><%= rover.landing_x_axis %></td>
        <td><%= rover.landing_y_axis %></td>
        <td><%= rover.target_x_axis %></td>
        <td><%= rover.target_y_axis %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rover_path(rover), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rover_path(rover),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rover_path,
            :class => 'btn btn-primary' %>

app/views/rovers/new.html.erb
<%- model_class = Rover -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rovers/show.html.erb
<%- model_class = Rover -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:landing_x_axis) %>:</strong></dt>
  <dd><%= @rover.landing_x_axis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:landing_y_axis) %>:</strong></dt>
  <dd><%= @rover.landing_y_axis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:target_x_axis) %>:</strong></dt>
  <dd><%= @rover.target_x_axis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:target_y_axis) %>:</strong></dt>
  <dd><%= @rover.target_y_axis %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rovers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rover_path(@rover), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rover_path(@rover),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/version/index.html.erb
<table class="table table-hover">
  <caption>We at NASA are proud to announce that the project is going as per our "Mars - The red planet exploration" plan. We are now in the <b>version 1.02</b> of the plan.</caption>
  <thead>
    <tr>
      <th></th>
      <th>Mission</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="span2"><img src="/images/img1.jpg" class="img-rounded"></td>
      <td>Mars Reconnaissance Orbiter</td>
      <td>NASA's Mars Reconnaissance Orbiter is capturing unique views of Mars with the most powerful telescopic camera ever to another planet. Its five other scientific instruments are collecting data about the Red Planet. </td>
    </tr>
    <tr>
      <td class="span2"><img src="/images/img2.jpg" class="img-rounded"></td>
      <td>Mars Exploration Rovers</td>
      <td>Two powerful Mars rovers are on the red planet. They have far greater mobility than the 1997 Mars Pathfinder rover. Each rover carries a sophisticated set of instruments to search for evidence of liquid water that may have been present in the planet's past. The rovers are identical to each other, but are exploring different regions of Mars. </td>
    </tr>
    <tr>
      <td class="span2"><img src="/images/img3.jpg" class="img-rounded"></td>
      <td>Mars Express</td>
      <td>NASA is participating in Mars Express, a mission planned by the European Space Agency (ESA) and the Italian Space Agency. The mission is exploring the atmosphere and surface of Mars from polar orbit. </td>
    </tr>
    <tr>
      <td class="span2"><img src="/images/img4.jpg" class="img-rounded"></td>
      <td>Mars Odyssey</td>
      <td>2001 Mars Odyssey is an orbiting spacecraft designed to determine the composition of the planet's surface, to detect water and shallow buried ice, and to study the radiation environment. </td>
    </tr>
    <tr>
      <td class="span2"><img src="/images/img5.jpg" class="img-rounded"></td>
      <td>Mars Science Laboratory</td>
      <td>Building on the success of the two rover geologists that arrived at Mars in January 2004, the Mars Science Laboratory Curiosity rover, will assess whether Mars ever had an environment able to support small life forms called microbes. In other words, its mission is to determine the planet's "habitability." </td>
    </tr>
  </tbody>
</table>

<p class="lead">Twice as long and three times as heavy as the Mars Exploration Rovers Spirit and Opportunity, Curiosity will collect martian soil samples and rocks and analyze them for organic compounds and environmental conditions that could have supported microbial life now or in the past. </p>